# Kitche+Vagrant doc: https://github.com/test-kitchen/kitchen-vagrant/blob/master/README.md
driver:
  name: vagrant
  customize:
    cpus: 1
    memory: 1536

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1

verifier:
  name: inspec
  sudo: true

platforms:
  - name: centos66
    driver:
      box: 'centos-6.6'
  - name: centos67
    driver:
      box: 'bento/centos-6.7'
  - name: centos7
    driver:
      box: 'bento/centos-7.1'
  - name: ubuntu14
    driver:
      box: 'opscode-ubuntu-14.04'

suites:
  - name: default
    run_list:
      - recipe[ccc::upgrade]
    attributes:
    attributes:
      ccc:
        package_url: https://packagecloud.io/chef/stable/packages/el/6/chef-compliance-0.9.5-1.el6.x86_64.rpm/download
        package2_url: https://packagecloud.io/chef/stable/packages/el/6/chef-compliance-0.9.11-1.el6.x86_64.rpm/download
        initial_user: admin
        initial_pass: hEu29zDQR1tw8
