# Kitche+Vagrant doc: https://github.com/test-kitchen/kitchen-vagrant/blob/master/README.md
driver:
  name: vagrant
  customize:
    cpus: 1
    memory: 1536

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1

verifier:
  name: inspec
  sudo: true

platforms:
  - name: centos66
    driver:
      box: 'centos-6.6'
  - name: centos67
    driver:
      box: 'bento/centos-6.7'
  - name: centos7
    driver:
      box: 'bento/centos-7.1'
  - name: ubuntu14
    driver:
      box: 'opscode-ubuntu-14.04'

suites:
  - name: default
    run_list:
      - recipe[ccc::default]
    attributes:
    attributes:
      ccc:
        package_version: 0.9.7
        package2_version: :latest
        initial_user: admin
        initial_pass: heu29DQR1tw-w9gz
