# Kitche+Vagrant doc: https://github.com/test-kitchen/kitchen-vagrant/blob/master/README.md
driver:
  name: vagrant
  customize:
    cpus: 1
    memory: 1536

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1

verifier:
  name: inspec
  sudo: true

platforms:
  - name: centos67
    driver:
      box: 'bento/centos-6.7'
  - name: centos7
    driver:
      box: 'bento/centos-7.2'
  - name: ubuntu14
    driver:
      box: 'bento/ubuntu-14.04'

suites:
  - name: default
    run_list:
      - recipe[ccc::default]
    attributes:
    attributes:
      ccc:
        package_version: 'latest'
        package_repo: 'stable'
        initial_user: admin
        initial_pass: hEu29zDQR1tw8
